### ISSUE TITLE
Can't find correct download file

### ISSUE THREAD

**Issue by eboff** [philxan/DrumsetPatterns#2]
Hi, not sure if I'm just lost but I can't find the correct file to download. I can only find DrumsetPatterns-main which doesn't seem to open to the correct files as described in installation. Help please!

**Comment by philxan** [comment]
hi eboff, first off, which version of MuseScore are you using? Unfortunately DrumsetPatterns doesn't launch in MuseScore 4.4, and I'm working on a fix for it. It caught me a bit unawares :( 

If you're using an earlier version, then all patterns files (*.dp) need to be placed in the same location. Typically this will be under the MuseScore "Plugins" directory, under a directory for the plugin. For example, on mine its
<user Documents>\MuseScore4\Plugins\DrumsetPatterns-1.0

**Comment by philxan** [comment]
Closing issue as no reponse.
